# Generated by Django 4.2.4 on 2023-10-15 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
                name='category',
                field=models.CharField(choices=[('j', 'Job'), ('h', 'Hobby'), ('s', 'School')], default='j', max_length=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(max_length=200, null=True, verbose_name='Task title'),
        ),
    ]
