# Generated by Django 4.2.4 on 2023-10-16 07:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_project_alter_task_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 16, 7, 41, 19, 774590), editable=False),
        ),
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 16, 7, 41, 19, 774572)),
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(db_column='name', max_length=200, null=True, verbose_name='Task title'),
        ),
    ]
